### PR TITLE
Adding my profiles to the mix 

### PR DESCRIPTION
**Pull request by DexteR-mask**
by Jaspreet Singh
comments could be found in the files.

### CODE REVIEW

**Comment by 1coderookie** [comment]
Hi, thanks for the PR. 
I'll have a look at the files in detail and see where e.g. the differences to my cfg are, which obviously was the template for yours. If yours only differs in terms of different values being set, then I most likely won't take it, as that's something users have to find out for themself anyway. 
Same goes for the gcode file. Here (just had a quick glance) you used the name "default1" for the bedmesh, which for example isn't the best option for beginners as the default filename is just "default". 
If I'll take it/them, I'll upload the files manually then as I'll have to make some changes to them anyway (cleanups, filename, commenting the includes in the cfg for not being needed at the 1st start, changing the bedmesh name, etc...) then. 
I'll get back to you then (probably in a few days as I'm short on time right now, but I'll check it asap).

**Comment by DexteR-mask** [comment]
some specific constants have tuned for higher acurracy,  
Like bed mesh MIN,MAX which are specific to Kobra NEO
probe correct y offset is -2 to -3


Added intro Line at the start in gcode 
added comments where ever necessary

**Comment by 1coderookie** [comment]
Bedmesh MIN MAX values have to be set by how a user wants to have it. The problem here is that if they're set too close to the edges of the plate you'll get false readings due to the fact that we're having an inductive probe with a wider sensor area than e.g. a BL Touch. So that can result in a *decreased* accuracy rather than an increased accuracy.  
As for the y-offset of the ABL sensor: at least on all of the 6 printheads of the Neo(s) I have, the center of the sensor is located 4mm to the back of the nozzle (when looking at the printhead from the front) and not "-2 to -3".  I'll re-measure and validate it again tho to make sure I didn't do a mistake here in the past.

Intro line: you mean purge line? I had several users reporting problems with a purge line at the edge of the bed, either due to a problem with the bed, an incorrect placed PEI sheet or a large print. So I personally got rid of it in that example I'm offering and ppl can either use a skirt for purging or look up the code for a purge line then.  
I'm offering basic configs which should serve the beginner as a safe start - if one feels to finetune it, they can do as they like.   

I understand that adding comments about where to look out for e.g. determining the correct PA  value or e-steps/rotation distance in the printer.cfg is meant good, but besides the fact that I mentioned that source in the Calibration chapter of the infopage, it leads to a kinda overloaded and cluttered cfg file imho. If users want to add that to their own file as a note for themselve it's totally fine of course, but I don't feel to do so in the example files I offer. If I'd do so, I then would have to add those kind of comments and explanations to all of the settings for having consistency here. And that will definitely be an overload..     
I already added notes about certain settings (like the fan's cycle_time, the PA smooth_time etc) as an explanation, which already are 'too much' if you compare the file with the example printer.cfg for the Go that's available in the official Klipper repo, so I don't want to add even more where it's not really necessary imho.

**Comment by 1coderookie** [comment]
So I just added your files manually. I renamed them so that the names fit the scheme I chose. The only thing I changed now is that I deactivated the includes in the printer.cfg, just because so many users reached out in the past asking why they get error messages (reason: they didn't had those files..).  
Thanks for contributing!

**Pull request closed without merging**
